from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MonsterSealAssets: 


	# Click Rule Assets
	# description 
	C_ZDDJ = RuleClick(roi_front=(699,597,176,59), roi_back=(698,595,180,63), name="zddj")
	# 自动准备 
	C_ZDZB = RuleClick(roi_front=(610,30,144,50), roi_back=(610,29,147,53), name="zdzb")
	# 取消自动准备 
	C_QXZDZB = RuleClick(roi_front=(612,33,144,49), roi_back=(610,32,145,52), name="qxzdzb")


	# Image Rule Assets
	# 自动匹配 
	I_AUTO_MATCHING = RuleImage(roi_front=(698,598,180,64), roi_back=(698,598,180,64), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_auto_matching.png")
	# 判断是否在年的界面 
	I_M_CHECK = RuleImage(roi_front=(793,278,242,246), roi_back=(793,279,242,246), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_m_check.png")
	# 跳跳哥哥 
	I_TTGG = RuleImage(roi_front=(544,131,116,45), roi_back=(538,114,144,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_ttgg.png")
	# 椒图 
	I_JT = RuleImage(roi_front=(541,131,87,45), roi_back=(536,116,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_jt.png")
	# 骨女 
	I_GN = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_gn.png")
	# 饿鬼 
	I_EG = RuleImage(roi_front=(544,131,70,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_eg.png")
	# 二口女 
	I_EKN = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_ekn.png")
	# 海坊主 
	I_HFZ = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_hfz.png")
	# 鬼使黑 
	I_GSH = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_gsh.png")
	# 小松丸 
	I_XSW = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_xsw.png")
	# 日和坊 
	I_RHF = RuleImage(roi_front=(544,131,87,45), roi_back=(538,114,96,72), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_rhf.png")
	# description 
	I_YQFY = RuleImage(roi_front=(383,109,160,50), roi_back=(409,125,162,51), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_yqfy.png")
	# description 
	I_WAIT = RuleImage(roi_front=(759,20,72,67), roi_back=(748,8,100,100), threshold=0.8, method="Template matching", file="./tasks/MonsterSeal/res/res_wait.png")


	# List Rule Assets
	# 妖气封印 
	L_NAME = RuleList(folder="./tasks/MonsterSeal/res", direction="vertical", mode="ocr", roi_back=(427,191,121,369), size=(94, 64), 
					 array=["跳跳哥哥", "椒图", "骨女", "饿鬼", "二口女", "海坊主", "鬼使黑", "小松丸", "日和坊"])


	# Ocr Rule Assets
	# 检查是否在列表页 
	O_CHECK_LIST = RuleOcr(roi=(395,182,193,384), area=(393,181,198,390), mode="Single", method="Default", keyword="", name="check_list")
	# Ocr-description 
	O_ALL = RuleOcr(roi=(462,202,57,35), area=(402,191,180,53), mode="Single", method="Default", keyword="", name="all")
	# Ocr-description 
	O_TTGG = RuleOcr(roi=(432,267,119,40), area=(402,259,172,54), mode="Single", method="Default", keyword="", name="ttgg")
	# Ocr-description 
	O_JT = RuleOcr(roi=(459,334,64,40), area=(401,326,179,54), mode="Single", method="Default", keyword="", name="jt")
	# Ocr-description 
	O_GV = RuleOcr(roi=(460,402,64,36), area=(399,394,180,53), mode="Single", method="Default", keyword="", name="gv")
	# Ocr-description 
	O_EG = RuleOcr(roi=(457,469,71,40), area=(401,461,180,55), mode="Single", method="Default", keyword="", name="eg")
	# Ocr-description 
	O_EKN = RuleOcr(roi=(445,242,95,43), area=(402,237,172,54), mode="Single", method="Default", keyword="", name="ekn")
	# Ocr-description 
	O_HFZ = RuleOcr(roi=(445,314,90,35), area=(397,303,185,54), mode="Single", method="Default", keyword="", name="hfz")
	# Ocr-description 
	O_GSH = RuleOcr(roi=(443,377,97,43), area=(401,372,178,55), mode="Single", method="Default", keyword="", name="gsh")
	# Ocr-description 
	O_XSW = RuleOcr(roi=(445,445,91,43), area=(397,438,184,56), mode="Single", method="Default", keyword="", name="xsw")
	# Ocr-description 
	O_RHF = RuleOcr(roi=(447,517,88,34), area=(402,506,176,56), mode="Single", method="Default", keyword="", name="rhf")


	# Swipe Rule Assets
	# description 
	S_UP = RuleSwipe(roi_front=(396,456,190,65), roi_back=(392,251,197,71), mode="default", name="up")
	# description 
	S_DOWN = RuleSwipe(roi_front=(395,254,190,63), roi_back=(393,457,194,65), mode="default", name="down")


